// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBXnMAo_4S7-FyHAoC_jr_qwxRMScUfrI',
    appId: '1:498268971403:web:931986c6ca96f520638f8e',
    messagingSenderId: '498268971403',
    projectId: 'project-ai-chat-47736',
    authDomain: 'project-ai-chat-47736.firebaseapp.com',
    storageBucket: 'project-ai-chat-47736.firebasestorage.app',
    measurementId: 'G-X7REWLPGFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIJ6iNH1jsF5o8r19TsveFj0cy3lEcvbg',
    appId: '1:498268971403:android:ebafbfb3e73aeeb4638f8e',
    messagingSenderId: '498268971403',
    projectId: 'project-ai-chat-47736',
    storageBucket: 'project-ai-chat-47736.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv_sXJO-eUfzygRJi1M9WDztdjaQRU-zM',
    appId: '1:498268971403:ios:5e4d9625cc9c49fb638f8e',
    messagingSenderId: '498268971403',
    projectId: 'project-ai-chat-47736',
    storageBucket: 'project-ai-chat-47736.firebasestorage.app',
    iosBundleId: 'com.example.projectAiChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv_sXJO-eUfzygRJi1M9WDztdjaQRU-zM',
    appId: '1:498268971403:ios:5e4d9625cc9c49fb638f8e',
    messagingSenderId: '498268971403',
    projectId: 'project-ai-chat-47736',
    storageBucket: 'project-ai-chat-47736.firebasestorage.app',
    iosBundleId: 'com.example.projectAiChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBXnMAo_4S7-FyHAoC_jr_qwxRMScUfrI',
    appId: '1:498268971403:web:398e530831b90242638f8e',
    messagingSenderId: '498268971403',
    projectId: 'project-ai-chat-47736',
    authDomain: 'project-ai-chat-47736.firebaseapp.com',
    storageBucket: 'project-ai-chat-47736.firebasestorage.app',
    measurementId: 'G-3Q2M48D9M8',
  );
}
